# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybxOTIgjApaTxOCbo18FMkJmLryhudNF
"""

from flask import Flask, render_template, request
import joblib
import numpy as np
app = Flask(__name__, template_folder='templates')
@app.route('/')
def student():
   return render_template("index.html")
def ValuePredictor(to_predict_list):
    data1 = request.form['a']
    data2 = request.form['b']
    arr = np.array([[data1,data2]]).reshape((-1, 1))
    loaded_model = joblib.load('model.sav')
    result = loaded_model.predict(arr)
    return result[0]
@app.route('/',methods = ['POST', 'GET'])
def result():
   if request.method == 'POST':
    to_predict_list = request.form.to_dict()
    to_predict_list=list(to_predict_list.values())
    to_predict_list = list(map(float, to_predict_list))
    result = float(ValuePredictor(to_predict_list))
    return render_template("index.html",result = result)
if __name__ == '__main__':
   app.run(debug = True)