# -*- coding: utf-8 -*-
"""UAS BIML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bet-8mX_PcOzT-EGH5SVbFp6AJeBLl77
"""

# Import libraries
## Basic libs
import pandas as pd
import numpy as np
#library
import joblib
from sklearn.linear_model import LinearRegression
# Load dataset
index = pd.read_csv('/content/Indeks Pembangunan Manusia menurut Provinsi.csv',sep=';')

print(index.shape)
index

index.drop(['Provinsi'],axis=1,inplace=True)

# Import Libraries
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

#library
import numpy as np
import joblib
from sklearn.linear_model import LinearRegression
#dataset 
x_train,x_test,y_train,y_test=train_test_split(
    index.drop(columns=['[Metode Baru] Indeks Pembangunan Manusia menurut Provinsi'],axis=0),
    index['[Metode Baru] Indeks Pembangunan Manusia menurut Provinsi'],
    test_size=0.3)
#call model regression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
#save model
filename = 'model.sav'
joblib.dump(regressor, filename)
#load model
loaded_model = joblib.load(filename)
#prediction model
loaded_model.predict(x_test)